# -*- coding: utf-8 -*-
"""spotify_config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g_xSzuDVYFZyzVTNosVdiBBqzdyzKAVr
"""

config = {
    'client_id' : 'b241f8cbff674ba09a2ae12611f61e20',
    'client_secret' :'8e35369b97fd494fa35ef6c7d8cfc929'
}